### PR TITLE
Feature/update to groovy 4.x

### PR DESCRIPTION
**Pull request by royteeuwen**
This version contains the latest Groovyconsole, which works on Groovy 4.x, supporting things like java lambda's etc..

### CODE REVIEW

**Comment by royteeuwen** [comment]
Not sure why the build fails on Sonar? This is not something I changed

**Comment by royteeuwen** [comment]
@nhirrle  can you look at this?

**Comment by nhirrle** [comment]
> @nhirrle can you look at this?

Sure, will have a look. Thanks a lot for your contribution!

**Comment by nhirrle** [comment]
> Not sure why the build fails on Sonar? This is not something I changed

Fixed. Was some permission issue on sonar side, sorry for that

**Comment by nhirrle** [comment]
Hi @royteeuwen 

I checked out the branch and tested further. On Java 11 it works fine, haven't found any issues so far. Great!
Unfortunately the groovy-bundle doesn't start with Java8 which could be an issue for some clients on AEM 6.5 . 
What do you think on this? I would like to avoid producing another artifact just for java8 where we bundle an old groovy version but if we have to, hopefully only for aem-on prem, not 100% sure if AEMaaCS is always on Java11...

Let me know about your thoughts.

**Comment by royteeuwen** [comment]
Hey @nhirrle ,
Thats bizar, seeing as JDK 8 should be supported: https://groovy-lang.org/releasenotes/groovy-4.0.html#Groovy4.0-requirements

AEMaaCS is always running on Java11, so creating a release 7.0.0 which is only compatible with JDK11 AEM 6.5 and AEMaaCS is (for me) an option, but I will first check if I cant get it working in JDK 8.

**Comment by royteeuwen** [comment]
@nhirrle  I have created a new release for groovy console which will be compiled with Java 8, seeing as all code is in groovy anyway I wont lose any features ;)

**Review by nhirrle — APPROVED** [review]

**Pull request merged**
